WPИ-XM
------

*WPИ-XM is a free and open-source web server solution stack for professional PHP development on the Windows platform.*

The groundation of the server stack consists of NGINX, PHP and MariaDB. Additionally XDebug, XhProf and Webgrind were added for profiling and debugging purposes; phpMyAdmin for MySQL administration purposes; memcached and APC for caching.
The abbreviation WPИ-XM consists of the initial letters of Windows, PHP, NGINX, XDebug and MariaDB.


Official Website:   http://wpn-xm.org/

Twitter:            http://twitter.com/wpnxm/

Google Group:       http://groups.google.com/group/wpn-xm/

Github:             https://github.com/jakoch/WPN-XM/


== WPN-XM USES THE FOLLOWING THIRD PARTY SOFTWARE COMPONENTS ==

------

COMPONENT   VERSION LICENCE(S)         COPYRIGHT                          WEBSITE

Base Components

MariaDB     5.3.2   GNU GPL v2         © 2010-2011 Monty Program Ab.      http://mariadb.org/ + http://askmonty.org/
NGINX       1.1.10  New BSD License    © 2002-2011 Igor Sysoev.           http://nginx.org/
PHP         5.3.8   PHP License        © 1999-2011 The PHP Group.         http://www.php.net/


PHP Extensions

XDebug      2.1.2   Xdebug License     © 2002 - 2007 Derick Rethans.      http://xdebug.org/
APC
Memcached   2.2.6

Additional Tools

xhProf              Apache License v2  © 2010 - 2011 Facebook.            http://pecl.php.net/package/xhprof/
                                                                          https://github.com/facebook/xhprof/
Webgrind    1.0     New BSD License    © 2010 - J. Nygård, J. Oettinger.  https://github.com/jokkedk/webgrind/
phpMyAdmin  3.4.8   GNU GPL v2         © 2003 - 2011 phpMyAdmin DevTeam.  http://www.phpmyadmin.net/
Memcached   1.4.5

------

== STILL NOT CONVINCED? ==

Well, then go try a different Serverpack for Windows. I know you’ll come back.

Here’s a comprehensive list for your convenience:

* Overview                http://alternativeto.net/software/xampp/

* XAMPP for Windows       http://www.apachefriends.org/de/xampp-windows.html
* Zend Server CE          http://www.zend.com/de/products/server-ce/
* VertrigoServ            http://vertrigo.sourceforge.net/
* Bitname WAMPStack       http://bitnami.org/stack/wampstack
* NginxMP                 http://www.sourceforge.net/projects/nginxmp/
* EasyWemp                http://projects.javatic.net/p/easywemp/source/tree/master/make-dist
* XenStack                http://sourceforge.net/projects/xenstack/
* EasyPHP                 http://easyphp.org

== HOW TO BUILD THE INSTALLER ==

*Requirements*

* Windows OS
* Innosetup (http://www.jrsoftware.org/isinfo.php) or
* ISTools (optional) (http://sourceforge.net/projects/istool/)

*Build*

* open "wpn-xm.iss" with InnoSetup or ISTools
* compile it
* test it

*Regards, Jens-André Koch*