# This is an automatically generated vhost file.
# Beware! All modifications to the file will be lost, when it is regenerated by WPN-XM!

# the server directive is nginx\'s virtual host directive
server {
        # port to listen on. can also be set to an IP:PORT
        listen       127.0.0.1:80;

        # sets the domain[s] that this vhost server requests for
        # example: # server_name www.[domain].com [domain].com;
        server_name  %%vhost%%;

        # the document root of this vhost
        root           www/%%vhost%%;

        log_not_found off;

        # vhost specific access log
        access_log  logs/%%vhost%%.log  main;

        location / {
            index  index.php index.html index.htm;
        }

        # pass PHP files for processing to the cgi-daemon
        location ~ \.php$ {

            fastcgi_pass   127.0.0.1:9100;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
            include        fastcgi_params;
        }
}